name: Overnight Hackathon Submission
description: Click Here to Submit Your Hackathon Project
title: "[Project]: "
labels: ["submission", "needreview"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in the hackathon and creating your submission!
  - type: input
    id: name
    attributes:
      label: Name
      description: Enter your full name
      placeholder: Full Name
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address
      placeholder: foo@bar.com
    validations:
      required: true
  - type: input
    id: team-emails
    attributes:
      label: Email Addresses of Team Members
      description: Enter the email addresses of you team members separated by commas (if you have any)
      placeholder: foo1@bar.com, foo2@bar.com, foo3@bar.com,...
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: What have you built during the hackathon?
      placeholder: The project I created is...
    validations:
      required: true
  - type: textarea
    id: inspiration
    attributes:
      label: Inspiration behind the Project
      description: What is the story behind this project? Why did you choose to work on this specific idea?
      placeholder: The reason I chose this idea/project was...
    validations:
      required: true
  - type: textarea
    id: tech-stack
    attributes:
      label: Tech Stack
      description: How have you built this project? Mention the technologies/methods/platforms you used to build your project
      placeholder: The technologies I used...
    validations:
      required: true
  - type: dropdown
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Select the specific Problem Statement for your submission from the list below
      options:
        - "AI/ML: 1. Vernacular Content Moderation for Regional Social Media"
        - "AI/ML: 2. Intelligent Document Processing for Infrastructure Operations"
        - "AI/ML: 3. Agricultural Input Subsidy Leakage Detection"
        - "Cybersecurity: 4. UPI Transaction Fraud Pattern Detection"
        - "Cybersecurity: 5. HTTP Traffic Attack Pattern Analysis"
        - "Blockchain: 6. Cooperative Society Digital Ledger Transparency"
        - "Blockchain: 7. Digital Content Copyright Authentication"
        - "Mobile App: 8. Multilingual AI Loan Advisor Application"
        - "EdTech: 9. Vernacular STEM Learning Gap Analysis"
        - "EdTech: 10. Behavioral Analytics for Online Assessment Integrity"
        - "General: 11. Gig Worker Rights Verification System"
        - "General: 12. Intelligent Candidate Discovery and Matching Platform"
    validations:
      required: true 

    validations:
      required: true
  - type: input
    id: project-link
    attributes:
      label: Project Repo
      description: Share a public repo link of your project
      placeholder: https://github.com/github-id/project-repo
    validations:
      required: true
  - type: input
    id: ppt-link
    attributes:
      label: Presentation (PPT) Link
      description: Share a publicly visible presentation (PPT) link of your project
      placeholder: https://docs.google.com/presentation/d/your-presentation-id
    validations:
      required: true
  - type: input
    id: demo-link
    attributes:
      label: Demo Video/Photos
      description: Share a publicly visible demo video/photos link of your project
      placeholder: https://www.youtube.com/watch?v=9IBaX1avYWc
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else?
      description: Any other feedback, queries or information, you would like to share with us?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Rules and Code of Conduct
      description: By submitting this issue, you agree to follow our Rules and Code of Conduct.
      options:
        - label: I agree to follow this hackathon's Rules and Code of Conduct
          required: true
